/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiket;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author mamur
 */
public class Home extends javax.swing.JFrame {

    Connection conn;
    Statement statement;
    ResultSet resultSet;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        ConnectionDB.getKoneksi();  
        fnama.requestFocus();
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        hanak.setVisible(false);
        sanak.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        
       
        
//        Mmbuat ID passenger Otomatis
          autoid();
//        Memanggil Nama Kereta Api
//        kereta();
//        Mengambil Tanggal Sekarang
        Date date = new Date();
        datee.setDate(date); 
//        Memanggil Data Kelas
       // kelas();
      // harga1();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sanak = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Bus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sjumlah = new javax.swing.JSpinner();
        fbayar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cclass = new javax.swing.JComboBox<>();
        ltotal = new javax.swing.JLabel();
        lkembali = new javax.swing.JLabel();
        datee = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        faddress = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        hdewasa = new javax.swing.JLabel();
        hanak = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        departure‏ = new javax.swing.JLabel();
        arrived = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JSpinner();
        btnsimpan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(22, 66, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(864, 432));

        jPanel2.setBackground(new java.awt.Color(22, 66, 70));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 162, 174));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 162, 174));
        jLabel1.setText("Passenger Name  :");

        fnama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fnama.setForeground(new java.awt.Color(255, 162, 174));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 162, 174));
        jLabel2.setText("From                  :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 162, 174));
        jLabel4.setText("Destination          :");

        destination.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        destination.setForeground(new java.awt.Color(255, 162, 174));
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Tujuan --", "Jakarta", "Bandung", "Yogyakarta", "Palembang" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 162, 174));
        jLabel5.setText("ID passenger       :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 162, 174));
        jLabel6.setText("Quantity   :");

        sanak.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        sanak.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anak(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 162, 174));
        jLabel9.setText("Rp.");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 162, 174));
        jLabel12.setText("Total         :");

        fid.setEditable(false);
        fid.setBackground(new java.awt.Color(204, 204, 255));
        fid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fid.setForeground(new java.awt.Color(255, 162, 174));
        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 162, 174));
        jLabel13.setText("Bus                    :");

        Bus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Bus.setForeground(new java.awt.Color(255, 162, 174));
        Bus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Bus --", "Damri", "Royal", "Puspajaya" }));
        Bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 162, 174));
        jLabel14.setText("Amount     :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 162, 174));
        jLabel15.setText("Reference   :");

        sjumlah.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        sjumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dewasa(evt);
            }
        });

        fbayar.setBackground(new java.awt.Color(204, 204, 255));
        fbayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fbayar.setForeground(new java.awt.Color(255, 162, 174));
        fbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbayarActionPerformed(evt);
            }
        });
        fbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayar(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 162, 174));
        jLabel16.setText("Class                  :");

        cclass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cclass.setForeground(new java.awt.Color(255, 162, 174));
        cclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Class --", "Eksekutif", "Bisnis", "Ekonomi" }));
        cclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas(evt);
            }
        });

        ltotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ltotal.setForeground(new java.awt.Color(255, 162, 174));
        ltotal.setText("0");

        lkembali.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lkembali.setForeground(new java.awt.Color(255, 162, 174));
        lkembali.setText("0");

        datee.setForeground(new java.awt.Color(255, 162, 174));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 162, 174));
        jLabel3.setText("Address              :");

        faddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        faddress.setForeground(new java.awt.Color(255, 162, 174));

        b5.setEditable(false);
        b5.setForeground(new java.awt.Color(255, 162, 174));

        hdewasa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hdewasa.setForeground(new java.awt.Color(255, 162, 174));
        hdewasa.setText("0");

        hanak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hanak.setForeground(new java.awt.Color(255, 162, 174));
        hanak.setText("0");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 162, 174));
        jLabel25.setText("/ Org");

        from.setEditable(false);
        from.setBackground(new java.awt.Color(204, 204, 255));
        from.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        from.setForeground(new java.awt.Color(255, 162, 174));
        from.setText("Bandar Lampung");

        departure‏.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        departure‏.setForeground(new java.awt.Color(255, 162, 174));
        departure‏.setText("00.00 WIB");

        arrived.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        arrived.setForeground(new java.awt.Color(255, 162, 174));
        arrived.setText("00.00 WIB");

        b1.setEditable(false);

        b2.setEditable(false);
        b2.setForeground(new java.awt.Color(255, 162, 174));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setEditable(false);
        b3.setForeground(new java.awt.Color(255, 162, 174));

        b4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        b4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                b4dewasa(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cclass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bus, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faddress, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(departure‏)
                                    .addComponent(arrived)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(sanak, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel14))
                                                .addGap(16, 16, 16))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fbayar)
                                            .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datee, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(sjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hdewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(202, 202, 202)
                                            .addComponent(hanak, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(fid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(fnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departure‏, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrived, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(Bus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cclass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(datee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(sjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hdewasa)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sanak, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hanak))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnsimpan.setBackground(new java.awt.Color(22, 66, 70));
        btnsimpan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 162, 174));
        btnsimpan.setText("Save");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Staff");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pasenger Data");
        jMenu2.setActionCommand("Passenger Data");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void autoid(){
       try{
            conn = ConnectionDB.getKoneksi();
            String sql = "SELECT COUNT(id) as kode FROM passenger";
            statement = conn.createStatement();
            resultSet = statement.executeQuery(sql);
            while(resultSet.next()){
                String kode = resultSet.getString("kode");
                int a = Integer.parseInt(kode);
                int b = a+1;
                fid.setText("TN."+b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
 
    private void dewasa(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dewasa
        int a = (int) sjumlah.getValue();
        int b = Integer.parseInt(hdewasa.getText());
        int c = a*b;
        ltotal.setText("Rp. "+c);
        b1.setText(""+c);
        
    }//GEN-LAST:event_dewasa

    private void bayar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayar
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          if(sanak.getValue().equals(0)){ 
            int a = Integer.parseInt(b1.getText());
            int b = Integer.parseInt(fbayar.getText());
            int c = b-a;
            lkembali.setText("Rp. "+c);
          }else{
            int a = Integer.parseInt(b2.getText());
            int b = Integer.parseInt(fbayar.getText());
            int c = b-a;
            lkembali.setText("Rp. "+c);
          }
      }
    }//GEN-LAST:event_bayar

    private void BusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusActionPerformed

        if(Bus.getSelectedItem().equals("Damri")){
        b4.setValue(1);
        Bus.setSelectedIndex(1);
       }else if(Bus.getSelectedItem().equals("Royal")){
       b4.setValue(2);
       Bus.setSelectedIndex(2);
       }
       else if(Bus.getSelectedItem().equals("Puspajaya")){
       b4.setValue(3);
       Bus.setSelectedIndex(3);
       }

       if(Bus.getSelectedItem().equals("Damri") && destination.getSelectedItem().equals("Jakarta")){
            departure‏.setText("08.30 WIB");
            arrived.setText("20.19 WIB");
        }else if(Bus.getSelectedItem().equals("Damri") && destination.getSelectedItem().equals("Bandung")){
            departure‏.setText("06.30 WIB");
            arrived.setText("09.45 WIB");
        }else if(Bus.getSelectedItem().equals("Damri") && destination.getSelectedItem().equals("Yogyakarta")){
            departure‏.setText("07.20 WIB");
            arrived.setText("16.15 WIB");
        }else if(Bus.getSelectedItem().equals("Damri") && destination.getSelectedItem().equals("Palembang")){
            departure‏.setText("06.15 WIB");
            arrived.setText("13.45 WIB");
        }
            
            //Argo Parahyangan
        else if(Bus.getSelectedItem().equals("Royal") && destination.getSelectedItem().equals("Jakarta")){
            departure‏.setText("07.30 WIB");
            arrived.setText("19.19 WIB");
        }else if(Bus.getSelectedItem().equals("Royal") && destination.getSelectedItem().equals("Bandung")){
            departure‏.setText("08.30 WIB");
            arrived.setText("11.45 WIB");
        }else if(Bus.getSelectedItem().equals("Royal") && destination.getSelectedItem().equals("Yogyakarta")){
            departure‏.setText("09.20 WIB");
            arrived.setText("18.15 WIB");
        }else if(Bus.getSelectedItem().equals("Royal") && destination.getSelectedItem().equals("Palembang")){
            departure‏.setText("08.15 WIB");
            arrived.setText("15.45 WIB");
        }
            
            //Lodaya
        else if(Bus.getSelectedItem().equals("Puspajaya") && destination.getSelectedItem().equals("Jakarta")){
            departure‏.setText("08.15 WIB");
            arrived.setText("20.05 WIB");
        }else if(Bus.getSelectedItem().equals("Puspajaya") && destination.getSelectedItem().equals("Bandung")){
            departure‏.setText("10.30 WIB");
            arrived.setText("14.45 WIB");
        }else if(Bus.getSelectedItem().equals("Puspajaya") && destination.getSelectedItem().equals("Yogyakarta")){
            departure‏.setText("07.20 WIB");
            arrived.setText("14.15 WIB");
        }else if(Bus.getSelectedItem().equals("Puspajaya") && destination.getSelectedItem().equals("Palembang")){
            departure‏.setText("07.15 WIB");
            arrived.setText("14.45 WIB");
        }
    }//GEN-LAST:event_BusActionPerformed

    private void simpan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan
        
        try{
            conn = ConnectionDB.getKoneksi();
            String sql = "INSERT INTO passenger VALUES('"+fid.getText()+
                    "','"+fnama.getText()+
                    "','"+faddress.getText()+
                    "','"+from.getText()+
                    "','"+destination.getSelectedItem()+
                    "','"+departure.getText()+
                    "','"+arrived.getText()+
                    "','"+datee.getDate()+
                    "','"+Bus.getSelectedItem()+
                    "','"+cclass.getSelectedItem()+
                    "','"+ltotal.getText()+
                    "','"+sjumlah.getValue()+"')";
            statement = conn.createStatement();
            statement.execute(sql);
            this.dispose();
            Main.oke();
            
           /** 
            String reportName = "src/report/Tiket.jasper";
            HashMap parameter = new HashMap();
            parameter.put("per_id",this.fid.getText());
            JasperPrint jPrint = JasperFillManager.fillReport(reportName, parameter, Koneksi.getKoneksi());
            JasperViewer.viewReport(jPrint, false);*/
            
            
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_simpan

    private void kelas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas
        
        if(cclass.getSelectedItem().equals("Eksekutif")){
            b5.setText("eksekutif");
        }else if(cclass.getSelectedItem().equals("Bisnis")){
            b5.setText("bisnis");
        }else if(cclass.getSelectedItem().equals("Ekonomi")){
            b5.setText("ekonomi");
        }
        
        conn = ConnectionDB.getKoneksi();
        
        if(cclass.getSelectedItem().equals("Eksekutif")){
            try{    
                statement = conn.createStatement();
                
                String sql1 = "SELECT * FROM hargaticket WHERE id='1'";
                resultSet = statement.executeQuery(sql1);
                while(resultSet.next()){
                    hdewasa.setText(resultSet.getString("price"));
                }
            
                String sql2 = "SELECT * FROM hargaticket WHERE id='1'";
                resultSet = statement.executeQuery(sql2);
                while(resultSet.next()){
                    hanak.setText(resultSet.getString("price"));
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        }else if((cclass.getSelectedItem().equals("Ekonomi"))){
            try{    
                statement = conn.createStatement();
                
                String sql1 = "SELECT * FROM hargaticket WHERE id='2'";
                resultSet = statement.executeQuery(sql1);
                while(resultSet.next()){
                    hdewasa.setText(resultSet.getString("price"));
                }
            
                String sql2 = "SELECT * FROM hargaticket WHERE id='2'";
                resultSet = statement.executeQuery(sql2);
                while(resultSet.next()){
                    hanak.setText(resultSet.getString("price"));
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        } else if(cclass.getSelectedItem().equals("Bisnis")){
            try{    
                statement = conn.createStatement();
                
                String sql1 = "SELECT * FROM hargaticket WHERE id='3'";
                resultSet = statement.executeQuery(sql1);
                while(resultSet.next()){
                    hdewasa.setText(resultSet.getString("price"));
                }
            
                String sql2 = "SELECT * FROM hargaticket WHERE id='3'";
                resultSet = statement.executeQuery(sql2);
                while(resultSet.next()){
                    hanak.setText(resultSet.getString("price"));
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_kelas

    private void laporan(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan
        new passenger().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporan

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Staff().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void b4dewasa(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_b4dewasa

    }//GEN-LAST:event_b4dewasa
/***/
    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed
/***/
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void anak(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anak
        int a = Integer.parseInt(b1.getText());
        int m = Integer.parseInt(hanak.getText());
        int b = (int) sanak.getValue();
        int c = b*m;
        int d = c+a;
        ltotal.setText("Rp. "+d);
        b2.setText(""+d);
    }//GEN-LAST:event_anak

    private void fbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fbayarActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bus;
    private javax.swing.JLabel arrived;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JSpinner b4;
    private javax.swing.JTextField b5;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cclass;
    private com.toedter.calendar.JDateChooser datee;
    private javax.swing.JLabel departure‏;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JTextField faddress;
    private javax.swing.JTextField fbayar;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField from;
    private javax.swing.JLabel hanak;
    private javax.swing.JLabel hdewasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lkembali;
    private javax.swing.JLabel ltotal;
    private javax.swing.JSpinner sanak;
    private javax.swing.JSpinner sjumlah;
    // End of variables declaration//GEN-END:variables
}
